//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kuzmich_JewelryStore.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Браслети.
        /// </summary>
        public static string CatBracelets {
            get {
                return ResourceManager.GetString("CatBracelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сережки.
        /// </summary>
        public static string CatEarrings {
            get {
                return ResourceManager.GetString("CatEarrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намисто.
        /// </summary>
        public static string CatNecklaces {
            get {
                return ResourceManager.GetString("CatNecklaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каблучки.
        /// </summary>
        public static string CatRings {
            get {
                return ResourceManager.GetString("CatRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть мову.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі права захищені.
        /// </summary>
        public static string FooterRights {
            get {
                return ResourceManager.GetString("FooterRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        public static string JewelryCategory {
            get {
                return ResourceManager.GetString("JewelryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріал.
        /// </summary>
        public static string JewelryMaterial {
            get {
                return ResourceManager.GetString("JewelryMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string JewelryName {
            get {
                return ResourceManager.GetString("JewelryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        public static string JewelryPrice {
            get {
                return ResourceManager.GetString("JewelryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Матеріал&quot; повинно бути заповнено.
        /// </summary>
        public static string MaterialRequired {
            get {
                return ResourceManager.GetString("MaterialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Золото.
        /// </summary>
        public static string MatGold {
            get {
                return ResourceManager.GetString("MatGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перли.
        /// </summary>
        public static string MatPearl {
            get {
                return ResourceManager.GetString("MatPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срібло.
        /// </summary>
        public static string MatSilver {
            get {
                return ResourceManager.GetString("MatSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Назва&quot; повинно бути заповнено.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог прикрас.
        /// </summary>
        public static string NavCatalog {
            get {
                return ResourceManager.GetString("NavCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        public static string NavCategories {
            get {
                return ResourceManager.GetString("NavCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        public static string SideCategories {
            get {
                return ResourceManager.GetString("SideCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріали.
        /// </summary>
        public static string SideMaterials {
            get {
                return ResourceManager.GetString("SideMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ювелірний магазин Кузьміч.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вишукані прикраси з золота, срібла та коштовного каміння.
        /// </summary>
        public static string SiteSlogan {
            get {
                return ResourceManager.GetString("SiteSlogan", resourceCulture);
            }
        }
    }
}
